[package]
name = "resym_core"
version = "0.2.0"
edition = "2021"
rust-version = "1.67"
exclude = [
    "tests/data/*",
    "tests/snapshots/*",
]

[dependencies]
pdb = "0.8"
thiserror = "1.0"
log = "0.4"
rayon = "1.5"
crossbeam-channel = "0.5"
num_cpus = "1.13"
dashmap = { version = "5.2", features = ["rayon"] }
regex = "1.5"
similar = "2.1"

[dev-dependencies]
insta = "1.14"
