[package]
name = "resym"
version = "0.2.0"
edition = "2021"

[dependencies]
resym_core = { version = "0.2", path = "../resym_core" }

eframe = { version = "0.18", features = ["persistence"] }
tinyfiledialogs = "3.0"
serde = "1.0"
syntect = "5.0"
anyhow = "1.0"
log = "0.4"
memory_logger = { version = "0.1", features = ["blocking"] }
crossbeam-channel = "0.5"
