name: Build

on: [push]

jobs:
  build-latest-windows:
    name: Build on Windows - Latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build --all-features
        run: cargo build --all-features

      - name: Build --no-default-features
        run: cargo build --no-default-features
